### ISSUE TITLE
Will you consider adding an action button like UIAlertController?

### ISSUE THREAD

**Issue by haojianzong** [li-bei/HUD#2]
This will allow the HUD to have an interaction like UIAlertView. The user will have enough time to read the message, tap the button, and dismiss the HUD.

I am not sure whether this is a good design for the HUD project, feel free to skip this idea to keep it simple. I might just use a UIAlertView for this.

In the following example, there are too many text to read in 3 seconds:

![image](https://user-images.githubusercontent.com/4256824/116860547-4d4b7600-ac34-11eb-9ef7-e53cdfe7a9ff.png)

**Comment by li-bei** [comment]
Same with your thought, I think this feature is too heavy/complex for a HUD.

For your specific case, I think using `UIAlertController` is also not a good fit, maybe you can create custom view controller and presentation for this scenario incase there's too many stock accounts.

**Comment by haojianzong** [comment]
Make sense to me. Thanks for keeping this library simple.
