### ISSUE TITLE
Support continuous corner curve

### ISSUE THREAD

**Issue by ethanhuang13** [li-bei/HUD#3]
Suggest to support continuous corner curve as style option for iOS 13+.
`layer.cornerCurve = .continuous`

**Comment by cyanzhong** [comment]
Took a quick look, should be continous already https://github.com/li-bei/HUD/blob/main/Sources/HUD/Views/_HUDView.swift#L23

**Comment by li-bei** [comment]
@ethanhuang13 @ethanhuang13 Yes it's already a continuous corner. And the radius should be exactly same (I assume, checked the pixel pattern with my eyes 😅) with Apple Music/Podcasts.

**Comment by ethanhuang13** [comment]
Why I missed the line reading code on my phone 🤦‍♂️ Anyway, great job!
